name: Black formatter

on: [push, pull_request]
#on:
#  push:
#    paths:
#      - '**.py'
#      - '.github/workflows/black.yml'
#  pull_request:
#    paths:
#      - '**.py'
#      - '.github/workflows/black.yml'

jobs:
  black-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black
      - name: Run black check
        run: |
          python -m black --check .
